function aclActionEnums = values(~)
% VALUES Returns cell array containing constants of this enum type
% The order is the order in which they are declared.
%

% Copyright 2018 The MathWorks, Inc.

aclActionEnums = {...
    'ALL',...
    'EXECUTE',...
    'NONE',...
    'READ',...
    'READ_EXECUTE',...
    'READ_WRITE',...
    'WRITE',...
    'WRITE_EXECUTE',...
    };

end
